name: QuickHarvest
version: '${version}'
main: io.github.aratakileo.quickharvest.QuickHarvest
api-version: 1.13
authors: [ Arataki Leo ]
description: Plugin that let players on the server harvest the plants by pressing right click and automatic replant it again at the same moment!
website: https://github.com/aratakileo/quick-harvest-plugin
